apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-practical-task
  namespace: scc-practical-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc-practical-task
  template:
    metadata:
      labels:
        app: scc-practical-task
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15